[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/omaciel"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/OgMaciel"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/ogmaciel/"
[[social]]
  weight = 4
  name = "instagram"
  url = "http://instagram.com/ogmaciel"
[[social]]
  name = "rss"
  weight = 5
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"